#!/usr/bin/env python

# Written by Mike Julian - mike@mikejulian.com

import re
import os
from sys import argv
from subprocess import call

script, command, input = argv

mibName = None
snmpttConfOut = "/etc/snmp/snmptt-autogenerated.conf"

def getMibName(filename):
   pattern = re.compile("(\S*)\s*(DEFINITIONS ::= BEGIN)")
   mibCount = 0
   for match in re.findall(pattern, filename):
      mibCount += 1
      mibName = match[0].lower()
      if mibCount > 1:
         mibName == None
         return mibName
      elif mibCount == 1:
         return mibName
      elif mibCount < 1:
         mibName == None
         return mibName

def renameMib():
   for root, subFolders, files in os.walk(input):
      for filename in files:
         fullPath = os.path.join(root, filename)
         contents = open(fullPath).read()
         mibName = getMibName(contents)
         if mibName != None:
            if filename != mibName:
               print "Renaming MIB: %s to %s" % (fullPath, root + '/' + mibName)
               os.rename(fullPath, root + '/' + mibName)
            else:
               print "MIB already named properly: %s" % filename
         elif mibName == None:
            print "File is not a MIB or contains multiple MIB definitions: %s" % filename

def checkMib():
   for root, subFolders, files in os.walk(input):
      for filename in files:
         fullPath = os.path.join(root, filename)
         contents = open(fullPath).read()
         mibName = getMibName(contents)
         if mibName != None:
            call("smilint -l 2 " + fullPath, shell=True)
         elif mibName == None:
            print "File is not a MIB or contains multiple MIB definitions"

def createSnmpTtConf():
   devnull = open('/dev/null', 'w')
   for root, subFolders, files in os.walk(input):
      for filename in files:
         fullPath = os.path.join(root, filename)
         contents = open(fullPath).read()
         mibName = getMibName(contents)
         if mibName != None:
            print "Generating config: %s" % mibName
            call("snmpttconvertmib --in " + fullPath + " --out " + snmpttConfOut, shell=True, stderr=devnull, stdout=devnull)
         elif mibName == None:
            print "File is not a MIB or contains multiple MIB definitions"

if command == "checkmib":
   checkMib()
elif command == "renamemib":
   renameMib()
elif command == "convertmib":
   createSnmpTtConf()
else:
   print "Unrecognized command."
